language: objective-c
osx_image: xcode9.3

script:
  - set -o pipefail
  - swift package generate-xcodeproj
  - xcodebuild test -enableCodeCoverage YES -project Diff.xcodeproj -scheme Diff -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty
