language: objective-c
osx_image: xcode9.3
script:
  - set -o pipefail
  - xcodebuild -project Sdifft.xcodeproj -scheme Sdifft-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' -configuration Release ONLY_ACTIVE_ARCH=YES  -enableCodeCoverage YES test | xcpretty
  - bash <(curl -s https://codecov.io/bash) -cF ios -X fix --verbose
